
partyId: {{ .partyId }}
partyName: {{ .name }}

# containers images 
image:
  registry: {{ .registry | default "federatedai" }}
  isThridParty: {{ empty .registry | ternary  "false" "true" }}
  tag: 1.2.2-release
  pullPolicy: {{ .pullPolicy | default "IfNotPresent" }}

persistence:
  enabled: {{ .persistence | default "false" }}

{{ if .servingProxy }}
servingProxy: 
  include: {{ has "servingProxy" .modules }}
  ip: serving-proxy
  intraPort: 8879
  interPort: 8869
  type: NodePort
  nodePort: {{ .servingProxy.nodePort }}
  ingerssHost: {{ .servingProxy.ingerssHost | default "{{ .partyId }}.serving-proxy.kubefate.net" }}
  partyList:
    {{- range .servingProxy.partyList }}
    - partyId: {{ .partyId }}
      partyIp: {{ .partyIp }}
      partyPort: {{ .partyPort }}
    {{- end }}
  exchange:
    {{- with .servingProxy.exchange }}
    partyIp: {{ .ip }}
    partyPort: {{ .port }}
    {{- end }}
  {{- with .servingProxy }}
  {{- with .nodeSelector }}
  nodeSelector: 
  {{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- else }}
servingProxy: 
  include: true
  ip: serving-proxy
  intraPort: 8879
  interPort: 8869
  type: NodePort
  nodePort: 30110
  ingerssHost: {{ .partyId }}.serving-proxy.kubefate.net
  partyList:
    - partyId: 9999
      partyIp: 192.168.9.1
      partyPort: 30109
  nodeSelector: {}
{{- end }}

{{ if .servingProxy }}
servingRedis:
  include: {{ has "servingRedis" .modules }}
  ip: serving-redis
  port: 6379 
  type: ClusterIP
  {{- with .servingRedis }}
  password: {{ .password | default "fate_dev" }}
  subPath: {{ .subPath | default "fate_dev" }}
  existingClaim: {{ .existingClaim }}
  storageClass: {{ .storageClass | default "serving-redis" }}
  accessMode: {{ .accessMode | default "ReadWriteOnce" }}
  size: {{ .size | default "1Gi" }}
  {{- with .nodeSelector }}
  nodeSelector: 
  {{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- else }}
servingRedis:
  include: {{ has "servingRedis" .modules }}
  ip: {{ .externalRedisIp | default "serving-redis" }}
  port: {{ .externalRedisPort | default "6379" }} 
  type: ClusterIP
  password: {{ .externalRedisPassword | default "fate_dev" }}
  subPath: {{ .subPath | default "fate_dev" }}
  existingClaim: {{ .existingClaim }}
  storageClass: {{ .storageClass | default "serving-redis" }}
  accessMode: {{ .accessMode | default "ReadWriteOnce" }}
  size: {{ .size | default "1Gi" }}
  nodeSelector: {}
{{- end }}
{{- if .servingServer }}
servingServer:
  include: {{ has "servingServer" .modules }}
  ip: serving-server
  port: 8000
  nodePort: {{ .servingServer.nodePort }}
  type: {{ .servingServer.type | default "ClusterIP" }}
  fateflow:
    {{- with .servingServer.fateflow }}
    ip: {{ .ip }}
    port: {{ .port }}
    {{- end }}
  {{- with .servingServer }}
  subPath: {{ .subPath | default "fate_dev" }}
  existingClaim: {{ .existingClaim }}
  storageClass: {{ .storageClass | default "serving-redis" }}
  accessMode: {{ .accessMode | default "ReadWriteOnce" }}
  size: {{ .size | default "1Gi" }}
  {{- with .nodeSelector }}
  nodeSelector: 
  {{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- else }}
servingServer:
  include: true
  ip: serving-server
  port: 8000
  type: ClusterIP
  fateflow:
    ip: fateflow.fate-10000
    port: 9380
  nodeSelector:  {}
  subPath: ""
  existingClaim: ""
  storageClass: "serving-server"
  accessMode: ReadWriteOnce
  size: 1Gi
{{- end }}
