# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.lbrollsite.include }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollsite
  labels:
    fateMoudle: rollsite
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: rollsite
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: rollsite
{{ include "fate.labels" . | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "rollsite"
      containers:
        - name: exchange
          image: {{ .Values.image.registry }}/nginx:1.17
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9390
          volumeMounts:
            # - mountPath: /data/projects/fate/proxy/nginx/conf/route_table.yaml
            #   name: rollsite-confs
            #   subPath: route_table.yaml
            - mountPath: /data/projects/fate/proxy/nginx/conf/nginx.conf
              name: rollsite-confs
              subPath: nginx.conf
        - name: rollsite
          env:
          - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
            value: python
          image: {{ .Values.image.registry }}/eggroll{{ include "images.eggroll.suffix" . }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.modules.lbrollsite.resources}}
          resources:
          {{- range $key, $val := .Values.modules.lbrollsite.resources }}
            {{ $key }}:
{{ toYaml $val | indent 14 }}
          {{- end }}
          {{- end }}
          command:
          - bash
          - -c
          - |
            set -x
            mkdir -p /data/projects/fate/eggroll/logs/eggroll/
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll-audit.log
            ln -sf /dev/stdout /data/projects/fate/eggroll/logs/eggroll/eggroll-audit.log
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.log
            ln -sf /dev/stdout /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.log
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.err.log 
            ln -sf /dev/stderr /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.err.log
            java -Dlog4j.configurationFile=$${EGGROLL_HOME}/conf/log4j2.properties -cp $${EGGROLL_HOME}/lib/*:$${EGGROLL_HOME}/conf/ com.webank.eggroll.rollsite.EggSiteBootstrap -c $${EGGROLL_HOME}/conf/eggroll.properties
          ports:
            - containerPort: 9370
          volumeMounts:
            - mountPath: /data/projects/fate/eggroll/conf/route_table/
              name: rollsite-confs
            - mountPath: /data/projects/fate/eggroll/conf/eggroll.properties
              name: eggroll-confs
              subPath: eggroll.properties
      {{- with .Values.modules.lbrollsite.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.lbrollsite.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.lbrollsite.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      restartPolicy: Always
      volumes:
        - name: rollsite-confs
          configMap:
            name: rollsite-config
        - name: eggroll-confs
          configMap:
            name: eggroll-config
{{ end }}