name: fate-10000
namespace: fate-10000
chartName: fate
chartVersion: v1.4.4
partyId: 10000
registry: ""
pullPolicy: 
persistence: false
istio:
  enabled: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - client

rollsite: 
  type: NodePort
  nodePort: 30010
  exchange:
    ip: 192.168.1.1
    port: 30000
  partyList:
  - partyId: 9999
    partyIp: 192.168.9.1
    partyPort: 30009
  nodeSelector: {}

nodemanager:
  count: 3
  sessionProcessorsPerNode: 4
  storageClass: "nodemanagers"
  accessMode: ReadWriteOnce
  size: 2Gi
  list:
  - name: nodemanager
    nodeSelector: {}
    sessionProcessorsPerNode: 4
    subPath: "nodemanager"
    existingClaim: ""
    storageClass: "nodemanager"
    accessMode: ReadWriteOnce
    size: 1Gi

python:
  fateflowType: NodePort
  fateflowNodePort: 30109
  nodeSelector: {}

mysql: 
  nodeSelector: {}
  ip: mysql
  port: 3306
  database: eggroll_meta
  user: fate
  password: fate_dev
  subPath: ""
  existingClaim: ""
  storageClass: "mysql"
  accessMode: ReadWriteOnce
  size: 1Gi

#
#externalMysqlIp: mysql
#externalMysqlPort: 3306
#externalMysqlDatabase: eggroll_meta
#externalMysqlUser: fate
#externalMysqlPassword: fate_dev


servingIp: 192.168.9.1
servingPort: 30209
