name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.6.0
partyId: 9999
registry: ""
imageTag: ""
pullPolicy: 
imagePullSecrets: 
- name: myregistrykey
persistence: true
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client
  # - lbrollsite
  # - spark
  # - hdfs
  # - nginx
  # - rabbitmq

backend: eggroll

# host:
  # fateboard: 9999.fateboard.kubefate.net
  # client: 9999.notebook.kubefate.net
  # sparkUI: 9999.spark.kubefate.net
  # rabbitmqUI: 9999.rabbitmq.kubefate.net
  # pulsarUI: 9999.pulsar.kubefate.net
  
# rollsite: 
  # type: NodePort
  # nodePort: 30091
  # exchange:
    # ip: 192.168.0.1
    # port: 30000
  # partyList:
  # - partyId: 10000
    # partyIp: 192.168.0.1
    # partyPort: 30101
  # nodeSelector:
  # - disktype: ssd
  # tolerations:
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"
  # affinity:
  # polling:
    # enabled: true
    # type: server
    # # server:
      # # ip: 192.168.100.1
      # # port: 9370
    # clientList:
    # - partID: 9999
    # concurrency: 49


# lbrollsite:
  # type: NodePort
  # nodePort: 30091
  # size: "2M"
  # exchangeList:
  # - id: 9991
    # ip: 192.168.0.1
    # port: 30910
  # nodeSelector:
  # tolerations:
  # affinity:

# nodemanager:
  # count: 3
  # sessionProcessorsPerNode: 4
  # storageClass: "nodemanagers"
  # accessMode: ReadWriteOnce
  # size: 2Gi
  # list:
  # - name: nodemanager
    # nodeSelector:
      # kubernetes.io/hostname: localhost.localdomain
    # tolerations:
      # - key: "swapenable"
      #  operator: "Equal"
      #  value: "true"
      #  effect: "PreferNoSchedule"
    # affinity:
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #       - matchExpressions:
      #           - key: kubernetes.io/hostname
      #             operator: In
      #             values:
      #               - localhost.localdomain
      # podAntiAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #               - nodemanager
      #       topologyKey: kubernetes.io/hostname
    # sessionProcessorsPerNode: 4
    # subPath: "nodemanager"
    # existingClaim: ""
    # storageClass: "nodemanager"
    # accessMode: ReadWriteOnce
    # size: 1Gi

# python:
  # type: NodePort
  # httpNodePort: 30097
  # grpcNodePort: 30092
  # serviceAccountName: ""
  # nodeSelector:
  # tolerations:
  # affinity:
  # enabledNN: false
  # existingClaim: ""
  # storageClass: "python"
  # accessMode: ReadWriteMany
  # size: 1Gi
  # clustermanager:
    # cores_per_node: 16
    # nodes: 2
  # spark: 
    # cores_per_node: 20
    # nodes: 2
    # master: spark://spark-master:7077
    # driverHost: 
    # driverHostType: 
    # portMaxRetries: 
    # driverStartPort: 
    # blockManagerStartPort: 
    # pysparkPython: 
  # hdfs:
    # name_node: hdfs://namenode:9000
    # path_prefix:
  # rabbitmq:
    # host: rabbitmq
    # mng_port: 15672
    # port: 5672
    # user: fate
    # password: fate
  # pulsar:
    # host: pulsar
    # mng_port: 8080
    # port: 6650
  # nginx:
    # host: nginx
    # http_port: 9300
    # grpc_port: 9310

# client:
  # nodeSelector: 
  # subPath: ""
  # existingClaim: ""
  # storageClass: "client"
  # accessMode: ReadWriteOnce
  # size: 1Gi

# mysql: 
  # nodeSelector:
  # tolerations:
  # affinity:
  # ip: mysql
  # port: 3306
  # database: eggroll_meta
  # user: fate
  # password: fate_dev
  # subPath: ""
  # existingClaim: ""
  # storageClass: "mysql"
  # accessMode: ReadWriteOnce
  # size: 1Gi


# externalMysqlIp: mysql1
# externalMysqlPort: 33060
# externalMysqlDatabase: eggroll_meta1
# externalMysqlUser: fate1
# externalMysqlPassword: fate_dev1


# servingIp: 192.168.0.1
# servingPort: 30095
# serving:
  # useRegistry: false
  # zookeeper:
    # hosts:
    # - serving-zookeeper.fate-serving-9999:2181
    # use_acl: false


# spark:
  # master:
    # Image: "federatedai/spark-master"
    # ImageTag: "1.6.0-release"
    # replicas: 1
    # resources:
      # requests:
        # cpu: "1"
        # memory: "2Gi"
      # limits:
        # cpu: "1"
        # memory: "2Gi"
    # nodeSelector:
    # tolerations:
    # affinity:
    # type: ClusterIP
    # nodePort: 30977
  # worker:
    # Image: "federatedai/spark-worker"
    # ImageTag: "1.6.0-release"
    # replicas: 2
    # resources:
      # requests:
        # cpu: "2"
        # memory: "4Gi"
      # limits:
        # cpu: "4"
        # memory: "8Gi"
    # nodeSelector:
    # tolerations:
    # affinity:
    # type: ClusterIP
# hdfs:
  # namenode:
    # nodeSelector:
    # tolerations:
    # affinity:
    # type: ClusterIP
    # nodePort: 30900
  # datanode:
    # nodeSelector:
    # tolerations:
    # affinity:
    # type: ClusterIP
# nginx:
  # nodeSelector:
  # tolerations:
  # affinity:
  # type: ClusterIP
  # httpNodePort: 30093
  # grpcNodePort: 30098
  # exchange:
    # ip: 192.168.10.1
    # httpPort: 30003
    # grpcPort: 30008
  # route_table: 
    # 10000: 
      # proxy: 
        # - host: 192.168.0.1 
          # http_port: 30103
          # grpc_port: 30108 
      # fateflow: 
        # - host: 192.168.0.1
          # http_port: 30107
          # grpc_port: 30102
# rabbitmq:
  # nodeSelector:
  # tolerations:
  # affinity:
  # type: ClusterIP
  # nodePort: 30094
  # default_user: fate
  # default_pass: fate
  # user: fate
  # password: fate
  # route_table:
    # 10000:
      # host: 192.168.0.1
      # port: 30104


# pulsar:
  # nodeSelector:
  # tolerations:
  # affinity:
  # type: ClusterIP
  # httpNodePort: 30094
  # httpsNodePort: 30099
  # publicLB:
    # enabled: false
  # exchange:
    # ip: 192.168.10.1
    # port: 30000
    # domain: fate.org
  # route_table:
    # 10000:
      # host: 192.168.10.1
      # port: 30105
      # sslPort: 30109
      # proxy: ""