########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

apiVersion: v1
appVersion: "1.3.0"
description: A Helm chart for fate-exchange
name: fate-exchange
version: 1.3.0
