# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if not .Values.istio.enabled }}
{{- if .Values.modules.fateboard.include }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fateboard
  labels:
    fateMoudle: fateboard
{{ include "fate.labels" . | indent 4 }}
{{- if .Values.ingress.fateboard.annotations }}
  annotations:
{{ toYaml .Values.ingress.fateboard.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  {{- range .Values.ingress.fateboard.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        pathType: Prefix
        backend:
          service:
            name: fateboard
            port:
              number: 8080
  {{- end }}
  {{- if .Values.ingress.fateboard.tls }}
  tls:
{{ toYaml .Values.ingress.fateboard.tls | indent 4 }}
  {{- end }}

{{- end }}
{{- end }}