########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.egg.include }}
{{- $root := . -}}
{{- range .Values.eggList }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ $root.Values.partyId }}: {{ .egg }}
  name: {{ .egg }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ $root.Values.partyId }}: {{ .egg }}
  template:
    metadata:
      labels:
        {{ $root.Values.partyId }}: {{ .egg }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "egg"
      containers:
        - env:
          - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
            value: cpp 
          - name: LD_LIBRARY_PATH
            value: $LD_LIBRARY_PATH:/usr/local/lib:/data/projects/fate/eggroll/storage-service-cxx/third_party/lib
          - name: PYTHONPATH
            value: /data/projects/fate/eggroll/python
          - name: GLOG_log_dir
            value: /data/projects/fate/eggroll/storage-service-cxx/logs
          image: {{ $root.Values.image.registry }}/egg:{{ $root.Values.image.tag }}
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          name: {{ .egg }}
          ports:
            - containerPort: 7888
            - containerPort: 7778
          volumeMounts:
            - mountPath: /data/projects/fate/eggroll/egg/conf/egg.properties
              name: egg-confs
              subPath: egg.properties
            - mountPath: /data/projects/fate/eggroll/python/eggroll/conf/server_conf.json
              name: python-confs
              subPath: server_conf.json
            {{- if and $root.Values.nfspath ( $root.Values.nfsserver ) }}
            - mountPath: /data/projects/fate/data-dir
              subPath: {{ .egg }}-data-dir
              name: modules-data-persistent-storage
            {{- end }}
            - mountPath: /data/projects/fate/eggroll/egg/conf/applicationContext-egg.xml
              name: other-confs
              subPath: applicationContext-egg.xml
            - mountPath: /data/projects/fate/eggroll/egg/conf/log4j2.properties
              name: other-confs
              subPath: log4j2.properties
            - mountPath: /data/projects/fate/eggroll/egg/conf/processor-starter.sh
              name: other-confs
              subPath: processor-starter.sh
      {{ if .value}}
      nodeSelector:
        {{ .nodeLabel }}: {{ .value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: egg-confs
          configMap:
            name: egg-config
        - name: python-confs
          configMap:
            name: python-config
        {{- if and $root.Values.nfspath ( $root.Values.nfsserver ) }}
        - name: modules-data-persistent-storage
          hostPath: 
            path: /data/projects/fate/data-dir
            type: DirectoryOrCreate
        {{- end }}
        - name: other-confs
          configMap:
            name: egg-config-other
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ $root.Values.partyId }}: {{ .egg }}
  name: {{ .egg }}
spec:
  ports:
    - name: "7888"
      port: 7888
      targetPort: 7888
      protocol: TCP
    - name: "7778"
      port: 7778
      targetPort: 7778
      protocol: TCP
  type: {{ $root.Values.modules.egg.type }}
  selector:
    {{ $root.Values.partyId }}: {{ .egg }}
---
{{- end }}
{{ end }}