########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

version: '3'

networks:
  fate-network:
volumes:
  fate_flow_logs:
services:
  federation:
    image: "${PREFIX}/federation:${TAG}"
    ports:
      - "9394:9394"
    volumes:
      - ./confs/federation/conf:/data/projects/fate/federation/conf
    networks:
      - fate-network

  proxy:
    image: "${PREFIX}/proxy:${TAG}"
    ports:
      - "9371:9370"
    volumes:
      - ./confs/proxy/conf:/data/projects/fate/proxy/conf
    networks:
      - fate-network

  fateboard:
    image: "${PREFIX}/fateboard:${TAG}"
    ports:
      - "8080:8080"
    volumes:
      - ./confs/fateboard/conf:/data/projects/fate/fateboard/conf
      - fate_flow_logs:/data/projects/fate/python/logs
    networks:
      - fate-network
    depends_on:
      - meta-service

  roll:
    image: "${PREFIX}/roll:${TAG}"
    expose:
      - 8011
    volumes:
      - ./confs/roll/conf:/data/projects/fate/roll/conf
    networks:
      - fate-network
    depends_on:
      - meta-service

  egg:
    image: "${PREFIX}/egg:${TAG}"
    expose:
      - 7888
      - 7778
      - 50001
      - 50002
      - 50003
      - 50004
    environment:
      - PYTHONPATH=python.path=/data/projects/fate/python
    volumes:
      - ./confs/egg/conf:/data/projects/fate/egg/conf
      - ./confs/python/arch/conf/server_conf.json:/data/projects/fate/python/arch/conf/server_conf.json
      - ./confs/python/arch/conf/settings.py:/data/projects/fate/python/arch/conf/settings.py
      - ./confs/python/conf:/data/projects/fate/python/conf
    networks:
      - fate-network

  fateflow:
    image: "${PREFIX}/python:${TAG}"
    ports:
      - "9360:9360"
      - "9380:9380"
    restart: always
    volumes:
      - ./confs/python/arch/conf:/data/projects/fate/python/arch/conf
      - ./confs/python/conf:/data/projects/fate/python/conf
      - ./confs/python/fate_flow/settings.py:/data/projects/fate/python/fate_flow/settings.py
      - fate_flow_logs:/data/projects/fate/python/logs
    depends_on:
      - redis
      - meta-service
      - proxy
      - roll
      - egg
    command: /bin/bash -c "sleep 10; source /data/projects/fate/venv/bin/activate; cd python/fate_flow && python fate_flow_server.py"
    networks:
      - fate-network

  meta-service:
    image: "${PREFIX}/meta-service:${TAG}"
    expose:
      - 8590
    volumes:
      - ./confs/meta-service/conf:/data/projects/fate/meta-service/conf
    depends_on:
      - mysql
    networks:
      - fate-network

  mysql:
    image: "mysql"
    expose:
      - 3306
    volumes:
      - ./confs/mysql/init:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fate_dev
      MYSQL_DATABASE: fate
      MYSQL_USER: fate
      MYSQL_PASSWORD: fate_dev
    networks:
      - fate-network

  redis:
    image: "redis"
    expose:
      - 6379
    command: redis-server --requirepass fate_dev
    volumes:
      - ./confs/redis/data:/data"
    networks:
      - fate-network

